language: php
php:
  - 5.4
  - 7.1
before_script:
  - composer require satooshi/php-coveralls --dev
script:
  - phpunit --coverage-clover build/logs/clover.xml
after_script:
  - php vendor/bin/coveralls -v
